#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Usage: $(basename $0) <TOKEN>"
  exit 1
fi

TOKEN=$1

# install xcode-select (for git)
echo "#; install Xcode Command Line Tools (for git)"
sudo xcode-select -p &>/dev/null || xcode-select --install

# define remote yadm function
source /dev/stdin <<< "$(curl -fsSL bootstrap.yadm.io)"

# clone dotfiles repo and run the bootstrap script
yadm clone --bootstrap "https://${TOKEN}@github.com/sn1elsen/dotfiles.git"
